version: "3.9"

volumes:
  postgres:
    driver: local

services:
  app: 
    build: .
    ports: 
      - '3333:3333'

  postgres:
    image: postgres
    volumes: 
      - postgres:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports: 
      - '5432:5432'

